### ISSUE TITLE
Enviroment

### ISSUE THREAD

**Issue by ldkong1205** [KU-CVLAB/MaskingDepth#1]
Hi @JongBeomBaek @seong0905, thank you for open-souring your work!

Regarding the environment for running experiments, can you provide the complete list of packages and libraries (and their versions) used? I noticed that you are using docker but I haven't used it before. Thank you for your help.

**Comment by ldkong1205** [comment]
By the way, can you also provide the config files for training on the NYU Depth V2 dataset? Thanks in advance!

**Comment by JongBeomBaek** [comment]
Thank you for your interest in our work.
you should install the packages following below
- dotmap
- wandb
- scikit-image 
- einops
- timm
(we confirmed that the code works even in the latest version of the package.)

and we additionally uploaded the config file for training on the NYU Depth V2 dataset.
please check this file.

If you have any problems please leave issue again :)
