### ISSUE TITLE
About the train time

### ISSUE THREAD

**Issue by uyo9ko** [KU-CVLAB/MaskingDepth#2]
Hello, thank you for your work. I was wondering if you could provide me with some information regarding the total training time for the NYU and KITTI experiments? Specifically, I'm curious how many NVIDIA RTX 3090 GPUs were used during the training process. Thank you for your help.

**Comment by seong0905** [comment]
Thank you for your interest in our work.

We used four NVIDIA RTX 3090 GPUs for the experiment, and the experiment took approximately one day.

**Comment by uyo9ko** [comment]
thank you！
